version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
    - framework: net471
    - framework: netcoreapp2.2
before_build:
- ps: >-
    dotnet restore .\demos\PuppeteerSharpDemos-Local.sln
build:
  project: .\demos\PuppeteerSharpDemos-Local.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test_script:
- cmd: >-
    cd .\demos\PuppeteerSharpPdfDemo

    dotnet run -p PuppeteerSharpPdfDemo-Local.csproj -f %framework% auto-exit