namespace PuppeteerSharp.PageCoverage
{
    /// <summary>
    /// Set of configurable options for coverage.
    /// </summary>
    public class CoverageStartOptions
    {
        /// <summary>
        /// Whether to reset coverage on every navigation. Defaults to <c>true</c>.
        /// </summary>
        public bool ResetOnNavigation { get; set; } = true;

        /// <summary>
        /// Whether anonymous scripts generated by the page should be reported.
        /// </summary>
        /// <remarks>
        /// Anonymous scripts are ones that don't have an associated url.
        /// These are scripts that are dynamically created on the page using `eval` or `new Function`.
        /// If <see cref="ReportAnonymousScripts"/> is set to `true`, anonymous scripts will have `__puppeteer_evaluation_script__` as their URL.
        /// </remarks>
        public bool ReportAnonymousScripts { get; set; }

        /// <summary>
        /// Whether the result includes raw V8 script coverage entries.
        /// </summary>
        public bool IncludeRawScriptCoverage { get; set; }
    }
}
